services:
  db:
    image: timescale/timescaledb:latest-pg16
    volumes:
      - ./.database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dev
  dbgui:
    image: dpage/pgadmin4
    ports:
      - 5433:80
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@example.com
      - PGADMIN_DEFAULT_PASSWORD=dev
  bot:
    build:
      context: .
      dockerfile: apps/backend/discord.bot/Dockerfile
    env_file:
      - .env.dev
    depends_on:
      - db
      - chartapi
    environment:
      ChartApiUri: http://chartapi:5000
      ConnectionStrings__DbConnection: "Host=db;Database=postgres;Username=postgres;Password=dev"
  chartapi:
    build:
      context: .
      dockerfile: apps/backend/chart.api/Dockerfile
    ports:
      - 5000:5000
  dbmigrations:
    build:
      context: .
      dockerfile: apps/backend/migrations/Dockerfile
    environment:
      ConnectionStrings__DbConnection: "Host=db;Database=postgres;Username=postgres;Password=dev"
    depends_on:
      - db
    entrypoint: /bin/bash -c "dotnet ef database update --project ./apps/backend/data.access"
    restart: "no"  # Ensures this service exits after completing the task