services:
  db:
    image: timescale/timescaledb:latest-pg16
    volumes:
      - ./.database:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always  # Automatically restarts on failure
  bot:
    build:
      context: .
      dockerfile: apps/backend/discord.bot/Dockerfile
    depends_on:
      - db
      - chartapi
    environment:
      Discord__BotToken: "${BotToken}"
      ChartApiUri: http://chartapi:5000
      ConnectionStrings__DbConnection: "Host=db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
    restart: always  # Ensures the bot restarts on failure

  chartapi:
    build:
      context: .
      dockerfile: apps/backend/chart.api/Dockerfile
    restart: always  # Ensures the service restarts on failure

  dbmigrations:
    build:
      context: .
      dockerfile: apps/backend/migrations/Dockerfile
    environment:
      ConnectionStrings__DbConnection: "Host=db;Database=${DB_NAME};Username=${DB_USER};Password=${DB_PASSWORD}"
    depends_on:
      - db
    entrypoint: /bin/bash -c "dotnet ef database update --project ./apps/backend/data.access"
    restart: on-failure  # Only restart if the service fails
